const actions = {
   STORE_ALL_CASES: "STORE_ALL_CASES",
   STORE_INDEXOF_CASE: "STORE_INDEXOF_CASE",
   STORE_CURRENT_ADMIN: "STORE_CURRENT_ADMIN",
   STORE_WYSIWYG: "STORE_WYSIWYG",
};

export default actions;
